### ISSUE TITLE
The todo section hides the input after some addition of todo's

### ISSUE THREAD

**Issue by pratik-codes** [pratik-codes/Dashlit#14]
The todo section in right bottom corner. Open that add 2-3 todos after adding todo the input is hidden. 

Expected Behaviour: 
It should not be hidden

**Comment by iamnazeef** [comment]
Hey Pratik, I would like to work on this issue, can you assign me to this if it is still open?

**Comment by Rai-Ayush** [comment]
@pratik-codes I would like to work on this issue. Can you assign it to me?

**Comment by pratik-codes** [comment]
Hi @Rai-Ayush asking you to please work on any other as this is closed in the last commit. Thanks!

**Comment by pratik-codes** [comment]
Closed as done
