### ISSUE TITLE
Add animation to links dropdown

### ISSUE THREAD

**Issue by pratik-codes** [pratik-codes/Dashlit#18]
Add animation when a link is rendered for the first time when drop down is open. 
Add animation on delete and addition of todo
Strictly use `framer-motion` for this. It is already configured in the app.

**Comment by ghost** [comment]
Hi @pratik-codes. Hope you are doing well! I would like to do this task. Can it be assigned?

**Comment by pratik-codes** [comment]
Sure @AlexisS05 assigning it to you.

**Comment by pratik-codes** [comment]
Closing this as completed. Thank you for your contribution @AlexisS05

**Comment by ghost** [comment]
Hi @pratik-codes. I hope you are doing well! I know this is late. But it was a pleasure working on your project! I had fun! I hope to see more progress. I hope to be able to contribute more sometime. But thank you for the opportunity on working on your project! I wish your project success! Have a great day! Take care and stay safe as well!

**Comment by pratik-codes** [comment]
Hey @AlexisS05 thank you soo much for taking the time and working on this. 😄
